auth logic updates

diff --git a/.github/workflows/master_charlotte-third-places.yml b/.github/workflows/master_charlotte-third-places.yml
--- a/.github/workflows/master_charlotte-third-places.yml
+++ b/.github/workflows/master_charlotte-third-places.yml
@@ -77,10 +77,15 @@ jobs:
 
       - name: Smoke Test
         run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d '{"House":"Martell"}' https://charlotte-third-places.azurewebsites.net/api/smoke-test)
-          if [ "$response" -eq 200 ]; then
-            echo "Smoke test passed with 200 OK."
-          else
-            echo "Smoke test failed with response code: $response. Please ensure there are no syntax errors in the changed function_app.py code. Furthermore, ensure the zipped and uploaded files from this deployment contains the expected file and folder structure. Azure Functions are very picky about structure."
-            exit 1
-          fi
+            response=$(curl -s -w "%{http_code}" -X POST -H "Content-Type: application/json" -H "x-functions-clientid: ${{ secrets.AZURE_FUNCTION_KEY }}" -d '{"House":"Martell"}' https://charlotte-third-places.azurewebsites.net/api/smoke-test)
+            http_status=$(echo "$response" | tail -n1)
+            response_body=$(echo "$response" | sed '$d')
+            echo "HTTP Status: $http_status"
+            echo "Response Body: $response_body"
+            if [ "$http_status" -eq 200 ]; then
+              echo "Smoke test passed with 200 OK."
+            else
+              echo "Smoke test failed with HTTP status: $http_status."
+              echo "Response body: $response_body"
+              exit 1
+            fi
