way simpler way of getting reviews data

diff --git a/.github/workflows/master_trigger-get-outscraper-reviews.yml b/.github/workflows/master_trigger-get-outscraper-reviews.yml
--- a/.github/workflows/master_trigger-get-outscraper-reviews.yml
+++ b/.github/workflows/master_trigger-get-outscraper-reviews.yml
@@ -1,11 +1,11 @@
-name: Trigger OutscraperReviewsRequest Azure Function
+name: Trigger GetOutscraperReviews Azure Function
 
 on:
   workflow_dispatch:
 
 # Ensures that only one instance of this workflow runs at a time
 concurrency: 
-  group: outscraper-reviews-request
+  group: get-outscraper-reviews
   cancel-in-progress: true
 
 jobs:
@@ -17,7 +17,7 @@ jobs:
           #!/bin/bash
           set -euo pipefail
       
-          API_URL="https://charlotte-third-places.azurewebsites.net/api/outscraper-reviews-request"
+          API_URL="https://charlotte-third-places.azurewebsites.net/api/get-outscraper-reviews"
       
           response=$(curl -s -w "\n%{http_code}" -X POST \
             -H "Content-Type: application/json" \
@@ -30,12 +30,12 @@ jobs:
           echo "HTTP Status: $http_status"
           echo "Response Body: $response_body"
       
-          if [ "$http_status" -eq 200 ]; then
-            echo "Action succeeded: Reviews request successfully processed."
+          if [[ $http_status -ge 200 && $http_status -lt 300 ]]; then
+              echo "Action succeeded: GetOutscraperReviews successfully executed."
           else
-            echo "Action failed: Unable to process reviews request."
-            echo "HTTP Status: $http_status"
-            echo "Response Body: $response_body"
-            exit 1
+              echo "Action failed: Unable to process GetOutscraperReviews."
+              echo "HTTP Status: $http_status"
+              echo "Response Body: $response_body"
+              exit 1
           fi
         shell: bash
